# Generated by Django 5.2.17 on 2026-10-01 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='banos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='habitaciones',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='m2_construidos',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='inmuebles_app.tipoinmueble'),
        ),
        migrations.AlterField(
            model_name='tipoinmueble',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
